<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4026.18">
  <POU Name="MotorControl" Id="{44046851-75e9-4547-aa66-0c24d1c464a0}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK MotorControl
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>